 # Pandas Series - 25 Practice Questions

In [1]:
import numpy as np
import pandas as pd

## Series Creation

In [21]:
# Create a Series of 5 student names with custom roll numbers as indexes.
name = ['aaa','bbb','ccc','ddd','eee']
roll_no = [101,102,103,104,105]

pd.Series(name,index=roll_no)

101    aaa
102    bbb
103    ccc
104    ddd
105    eee
dtype: object

In [27]:
# Create a Series from a dictionary containing 5 product names and prices.
dict={
    'product1' : 20,
    'product2' : 30,
    'product3' : 40,
    'product4' : 50,
    'product5' : 80
    }
marks_Series = pd.Series(dict)
marks_Series

product1    20
product2    30
product3    40
product4    50
product5    80
dtype: int64

In [23]:
# Create a Series of monthly sales data for one year.
monthly_sales = [100,200,300,400,500,600,700,800,900,1000,1100,1200]
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
pd.Series(monthly_sales,index=months)

Jan     100
Feb     200
Mar     300
Apr     400
May     500
Jun     600
Jul     700
Aug     800
Sep     900
Oct    1000
Nov    1100
Dec    1200
dtype: int64

## Attributes

In [31]:
# Find the size, shape, dtype, index, and values of a Series.
marks_Series
print(marks_Series.size)
print(marks_Series.shape)
print(marks_Series.dtype)
print(marks_Series.index)
print(marks_Series.values)

5
(5,)
int64
Index(['product1', 'product2', 'product3', 'product4', 'product5'], dtype='object')
[20 30 40 50 80]

In [32]:
# Create a named Series and display its name attribute
marks_Series.name = 'marks'
marks_Series.name

'marks'

## Statistical Functions

In [36]:
# Create a Series of 20  stu_marks and find mean, median, max, and min.
stu_marks =[10,20,40,30,44,55,63,22,45,23,45,67,86,43,33,54,65,63,86,74]
print(np.mean(stu_marks))
print(np.median(stu_marks))
print(np.max(stu_marks))
print(np.min(stu_marks))

48.4
45.0
86
10

In [38]:
# Find the standard deviation and variance of employee salaries.
salaries = [50000,60000,70000,80000,90000]
print(np.std(salaries))
print(np.var(salaries))

14142.13562373095
200000000.0

In [39]:
# Use describe() and explain each statistic
marks_Series.describe()

count     5.000000
mean     44.000000
std      23.021729
min      20.000000
25%      30.000000
50%      40.000000
75%      50.000000
max      80.000000
Name: marks, dtype: float64

## Indexing & Slicing

In [59]:
# Access the 5th element
elements = [1,2,3,4,5,6,7,8,9]
elements[5]

6

In [62]:
# Extract values from positions 3 to 10.
elements[3:10]

[4, 5, 6, 7, 8, 9]

In [67]:
# Retrieve alternate values from a Series.
elements_series = pd.Series(elements)
elements_series[::2x]

0    1
2    3
4    5
6    7
8    9
dtype: int64

In [71]:
# Access multiple values using fancy indexing.
elements_series[[1,6,7,4]]

1    2
6    7
7    8
4    5
dtype: int64

## Sorting

In [83]:
# Sort a Series in ascending and descending order.
elements_series.sort_values()

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [84]:
elements_series.sort_values(ascending=False)

8    9
7    8
6    7
5    6
4    5
3    4
2    3
1    2
0    1
dtype: int64

In [93]:
# Sort a Series based on index labels.
elements_series.sort_index()

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

## Value Counts

In [97]:
# Create a Series of fruits and find frequency of each fruit
fruits = pd.Series(['Apple','Mango','Apple','Banana','Mango','Apple','Banana'])
print(fruits.value_counts())

Apple     3
Mango     2
Banana    2
Name: count, dtype: int64

## Data Modification

In [99]:
# Update a specific value using index label.
s = pd.Series([50,60,70], index=['A','B','C'])
s['B'] = 80
print(s)

A    50
B    80
C    70
dtype: int64

In [106]:
marks = [50,30,40,60]

In [114]:
# Increase all marks by 5
marks_series = pd.Series(marks)
new_marks = marks_series + 5
print(new_marks)

0    55
1    35
2    45
3    65
dtype: int64

In [113]:
# Find students score above 40
marks_series = pd.Series(marks)
print(marks_series[marks_series > 40])

0    50
3    60
dtype: int64

## Boolean Indexing

In [118]:
# Find all students scoring above 50.
marks_series = pd.Series(marks)
print(marks_series[marks_series > 50])

3    60
dtype: int64

In [121]:
# Find values between 40 and 80.
marks_series = pd.Series(marks)
print(marks_series[(marks_series > 40) & (marks_series < 80)])

0    50
3    60
dtype: int64

## Missing Values

In [134]:
# Create a Series with NaN values, remove them.
series  = pd.Series([1,2,3,np.nan,4,np.nan,5])
print(series.isnull().sum())
print(series.dropna())

2
0    1.0
1    2.0
2    3.0
4    4.0
6    5.0
dtype: float64